nname: Build and Deploy
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build-and-deploy:
    runs-on: windows-latest
 
    steps:
      - uses: actions/checkout@v2
 
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
 
      - name: Restore dependencies
        run: dotnet restore
 
      - name: Build
        run: dotnet build -c Release --no-restore
 
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
 
      - name: Publish
        run: dotnet publish -c Release -o ./publish
 
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name:  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./publish
